const services = [
  { number: "01", slug: "software-saas", title: "Software & SaaS", copy: "Purpose-built platforms, customer portals, and SaaS products engineered to scale with your ambition.", tags: ["Product strategy", "Web & mobile", "Cloud architecture"], image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1000&q=82", alt: "Software source code on a developer workstation" },
  { number: "02", slug: "ai-automation", title: "AI & Automation", copy: "Practical AI agents and intelligent workflows that remove friction from the work your team does every day.", tags: ["AI agents", "Workflow automation", "Data intelligence"], image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1000&q=82", alt: "Artificial intelligence network visualization" },
  { number: "03", slug: "digital-growth", title: "Growth & Advertising", copy: "Connected campaigns, content, and performance systems that turn attention into measurable momentum.", tags: ["Digital strategy", "Paid media", "Conversion design"], image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=82", alt: "Digital growth analytics displayed on a laptop" },
  { number: "04", slug: "ecommerce-marketplaces", title: "Commerce & Marketplaces", copy: "Digital storefronts and marketplace experiences designed to make discovery, purchase, and loyalty feel effortless.", tags: ["E-commerce", "Marketplaces", "Growth operations"], image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1000&q=82", alt: "Digital commerce payment experience" },
];
const capabilities = ["Web applications", "SaaS platforms", "AI agents", "Process automation", "IT solutions", "Performance marketing", "E-commerce", "Analytics"];
const clientScenes = [
  { title: "Product teams", label: "Software & SaaS", image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=82", alt: "A diverse product team collaborating around a table" },
  { title: "Technology leaders", label: "AI & Automation", image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=82", alt: "Technology professionals working together in a modern office" },
  { title: "Commerce builders", label: "E-commerce", image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=82", alt: "Customer using a digital commerce payment experience" },
  { title: "Growth partners", label: "Digital growth", image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=82", alt: "Business leaders meeting to discuss a growth strategy" },
];
export default function Home() {
  return <main>
    <nav className="nav"><a className="brand" href="#top" aria-label="Scorpio Analytics home"><span className="logo-crop"><img src="/scorpio-logo.png" alt="Scorpio Analytics" /></span></a><div className="nav-links" aria-label="Primary navigation"><a href="#about">About</a><a href="#services">Expertise</a><a href="#approach">Approach</a></div><a className="nav-cta" href="#contact">Contact us <span>&#8599;</span></a></nav>
    <section className="hero" id="top"><div className="hero-kicker"><span className="pulse"/> Digital systems for ambitious businesses</div><h1>Software and AI<br/><em>automation solutions.</em></h1><div className="hero-bottom"><p>Software, AI, growth, and commerce—designed as one connected engine for what your business becomes next.</p><a className="circle-link" href="#services" aria-label="Explore our expertise">↓</a></div><div className="agent-console" aria-label="Live agentic capabilities"><span className="agent-status"><i/> AGENTIC SYSTEM ONLINE</span><strong data-agent-text>Observe → Reason → Act</strong><small>Human-led. AI-accelerated.</small></div><div className="orbit" aria-hidden="true"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-core">S<span>A</span></div><span className="orbit-label label-one">BUILD</span><span className="orbit-label label-two">AUTOMATE</span><span className="orbit-label label-three">GROW</span></div></section>
    <section className="signal-strip" aria-label="Capabilities"><div className="signal-track">{[...capabilities,...capabilities].map((item,index)=><span key={`${item}-${index}`}>{item} <b>✦</b></span>)}</div></section>
    <section className="about section" id="about">
      <div className="section-intro"><span className="eyebrow">About us</span><div><h2>Technology with<br/><i>business purpose.</i></h2><p>Scorpio Analytics is a digital technology company helping organizations turn data, software, and artificial intelligence into practical business advantage.</p></div></div>
      <div className="about-layout"><div className="about-visuals"><div className="about-image reveal"><img src="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=84" alt="Modern glass business buildings reaching into the sky"/><div className="image-chip">Building what comes next</div></div><div className="about-secondary reveal"><img src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1000&q=82" alt="A technology team collaborating in a bright workspace"/><span>People + technology + momentum</span></div></div><div className="about-copy"><p>We work across software development, SaaS, AI automation, technology services, digital growth, and online commerce. Our role is to connect strategy with execution—so ideas become reliable systems, and systems create measurable momentum.</p><p className="about-detail">From an early product idea to enterprise-scale modernization, we help teams define the opportunity, design the experience, build the technology, and continuously improve results. Our work is grounded in measurable outcomes, transparent collaboration, and systems designed to evolve.</p><div className="about-stats"><div><b>6</b><span>Connected service disciplines</span></div><div><b>End-to-end</b><span>Strategy through optimization</span></div></div><div className="about-principles"><article><b>01</b><h3>Outcome-led</h3><p>We begin with the business result, then choose the right technology.</p></article><article><b>02</b><h3>Human-centered</h3><p>Every system is designed around the people who use and trust it.</p></article><article><b>03</b><h3>Built to evolve</h3><p>Modular foundations keep products ready for the next opportunity.</p></article></div></div></div>
    </section>    <section className="services section" id="services"><div className="section-intro"><span className="eyebrow">What we do</span><div><h2>One partner.<br/><i>Every digital lever.</i></h2><p>We connect technology, intelligence, and growth so every investment compounds instead of operating in a silo.</p></div></div><div className="service-grid">{services.map(service=><a className="service-card" key={service.number} href={`/services/${service.slug}/`} aria-label={`Email Scorpio Analytics about ${service.title}`}><div className="service-image"><img src={service.image} alt={service.alt} loading="lazy"/><span>{service.number}</span></div><div className="service-body"><div className="card-top"><span>OUR EXPERTISE</span><span className="card-arrow">&#8599;</span></div><h3>{service.title}</h3><p>{service.copy}</p><div className="tags">{service.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div></a>)}</div></section>
    <section className="client-gallery section" id="clients">
      <div className="section-intro gallery-intro"><span className="eyebrow">Who we build for</span><div><h2>Built around people.<br/><i>Designed for progress.</i></h2><p>We partner with the teams turning ambitious ideas into useful products, efficient operations, and sustainable growth.</p></div></div>
      <div className="client-grid">{clientScenes.map((scene,index)=><a className={`client-image card-${index+1}`} key={scene.title} href="#contact" aria-label={`Discuss solutions for ${scene.title}`}><img src={scene.image} alt={scene.alt} loading="lazy"/><div className="client-caption"><span>{scene.label}</span><h3>{scene.title}</h3><b>0{index+1}</b></div></a>)}</div>
      <p className="image-note">Focused on the people, products, and industries moving business forward.</p>
    </section>
    <section className="manifesto"><div className="manifesto-number">OUR POINT OF VIEW</div><p>Technology should not just support the business.</p><h2>It should move it.</h2><div className="manifesto-note"><span>STRATEGY</span><i>→</i><span>SYSTEMS</span><i>→</i><span>SCALE</span></div></section>
    <section className="data-world section">
      <div className="section-intro"><span className="eyebrow">Data in the real world</span><div><h2>From signals to<br/><i>intelligent action.</i></h2><p>We connect data foundations, intelligent automation, and digital experiences to help teams see clearly and act faster.</p></div></div>
      <div className="data-mosaic"><figure className="data-shot data-wide reveal"><img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1600&q=84" alt="Business analytics dashboard with data visualizations"/><figcaption><span>Decision intelligence</span><b>See the whole picture</b></figcaption></figure><figure className="data-shot reveal"><img src="https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=84" alt="Modern data center infrastructure"/><figcaption><span>Data foundations</span><b>Engineer for trust</b></figcaption></figure><figure className="data-shot reveal"><img src="https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=84" alt="Modern commercial architecture representing business growth"/><figcaption><span>Digital enterprise</span><b>Build for scale</b></figcaption></figure></div>
    </section>    <section className="approach section" id="approach"><div className="section-intro approach-intro"><span className="eyebrow">How we work</span><div><h2>Clarity before code.<br/><i>Outcomes before output.</i></h2></div></div><div className="steps"><article><span>01</span><div><h3>Find the leverage</h3><p>We map the opportunity, the bottlenecks, and the shortest path to meaningful impact.</p></div></article><article><span>02</span><div><h3>Build the system</h3><p>Cross-functional teams turn the strategy into a focused, resilient digital product.</p></div></article><article><span>03</span><div><h3>Compound the value</h3><p>We measure, refine, and scale what works—creating momentum beyond the initial launch.</p></div></article></div></section>
    <section className="contractors section" id="contractors">
      <div className="contractor-intro"><span className="eyebrow">Work with us</span><h2>Bring your craft.<br/><i>Build what matters.</i></h2><p>We welcome independent specialists across engineering, data, AI, design, marketing, and commerce. Tell us where you create your best work.</p><div className="talent-tags"><span>Software engineering</span><span>Data & AI</span><span>Product design</span><span>Cloud & IT</span><span>Digital marketing</span><span>E-commerce</span></div></div>
      <form className="contractor-form" id="contractor-form" action="https://formsubmit.co/support@scorpioanalytics.com" method="POST"><input type="hidden" name="_subject" value="New contractor application - Scorpio Analytics"/><input type="hidden" name="_template" value="table"/><input type="hidden" name="_next" value="https://scorpioanalytics.com/?submitted=contractor#contractors"/><input type="hidden" name="_url" value="https://scorpioanalytics.com/#contractors"/><input type="text" name="_honey" className="honey-field" tabIndex={-1} autoComplete="off"/><div className="field"><label htmlFor="contractor-name">Full name</label><input id="contractor-name" name="name" type="text" autoComplete="name" required placeholder="Your name"/></div><div className="field"><label htmlFor="contractor-email">Email address</label><input id="contractor-email" name="email" type="email" autoComplete="email" required placeholder="you@example.com"/></div><div className="field"><label htmlFor="contractor-phone">Phone</label><input id="contractor-phone" name="phone" type="tel" autoComplete="tel" placeholder="Optional"/></div><div className="field"><label htmlFor="contractor-skill">Primary expertise</label><select id="contractor-skill" name="expertise" required defaultValue=""><option value="" disabled>Select an area</option><option>Software engineering</option><option>Data & AI</option><option>Product design</option><option>Cloud & IT</option><option>Digital marketing</option><option>E-commerce</option><option>Other</option></select></div><div className="field"><label htmlFor="contractor-availability">Availability</label><select id="contractor-availability" name="availability" required defaultValue=""><option value="" disabled>Select availability</option><option>Immediately</option><option>Within 2 weeks</option><option>Within 1 month</option><option>Future opportunities</option></select></div><div className="field"><label htmlFor="contractor-portfolio">Portfolio or résumé link</label><input id="contractor-portfolio" name="portfolio" type="url" placeholder="https://"/></div><div className="field field-wide"><label htmlFor="contractor-message">Tell us about your work</label><textarea id="contractor-message" name="message" rows={5} required placeholder="Your experience, preferred projects, and what you would like to build..."/></div><label className="consent field-wide"><input type="checkbox" name="consent" required/><span>I agree that Scorpio Analytics may use this information to respond to my contractor inquiry.</span></label><div className="form-footer field-wide"><p>Your application will be securely delivered to the Scorpio Analytics team.</p><button type="submit">Submit application <span>&#8599;</span></button></div></form>
    </section>    <section className="contact" id="contact"><span className="eyebrow light">Let us make it real</span><div className="contact-content"><div><h2>Your next advantage<br/>starts with a <i>conversation.</i></h2><div className="contact-details"><a href="mailto:support@scorpioanalytics.com">support@scorpioanalytics.com</a><a href="tel:+917997777886">+91 79977 77886</a></div></div><a className="contact-button" href="mailto:support@scorpioanalytics.com"><span>Tell us what’s next</span><b>↗</b></a></div><footer><a className="brand footer-brand" href="#top"><span className="logo-crop footer-logo"><img src="/scorpio-logo.png" alt="Scorpio Analytics" /></span></a><div className="footer-meta"><a href="https://www.linkedin.com/company/142884752/" target="_blank" rel="noreferrer">LinkedIn ↗</a><button type="button" className="privacy-link" data-open-privacy>Privacy & cookies</button><span>© {new Date().getFullYear()} Scorpio Analytics</span></div></footer></section>
    <div className="cookie-banner" id="cookie-banner" role="dialog" aria-label="Cookie preferences" hidden><div><strong>Your privacy, your choice.</strong><p>We use essential cookies to make the site work. With your permission, optional analytics and marketing cookies help us improve it.</p></div><div className="cookie-actions"><button type="button" data-cookie="reject">Reject optional</button><button type="button" data-cookie="manage">Manage choices</button><button type="button" className="primary" data-cookie="accept">Accept all</button></div></div>
    <div className="privacy-modal" id="cookie-settings" role="dialog" aria-modal="true" aria-labelledby="cookie-title" hidden><div className="modal-card"><button className="modal-close" type="button" data-modal-close aria-label="Close">×</button><span className="eyebrow">Privacy controls</span><h2 id="cookie-title">Cookie preferences</h2><p>Choose which optional cookies Scorpio Analytics may use on this device.</p><label className="preference-row"><span><b>Essential</b><small>Required for security and saved preferences.</small></span><input type="checkbox" checked disabled/></label><label className="preference-row"><span><b>Analytics</b><small>Helps us understand how the website is used.</small></span><input id="cookie-analytics" type="checkbox"/></label><label className="preference-row"><span><b>Marketing</b><small>Supports relevant campaign measurement.</small></span><input id="cookie-marketing" type="checkbox"/></label><button className="save-preferences" type="button" data-cookie="save">Save preferences</button></div></div>
    <div className="privacy-modal" id="privacy-notice" role="dialog" aria-modal="true" aria-labelledby="privacy-title" hidden><div className="modal-card privacy-copy"><button className="modal-close" type="button" data-modal-close aria-label="Close">×</button><span className="eyebrow">Privacy notice</span><h2 id="privacy-title">How we handle information</h2><p>Scorpio Analytics collects only the information you choose to provide through contact and contractor inquiries. It is used to respond to your request, evaluate potential working relationships, and operate this website.</p><p>We do not sell personal information. Contractor form details are submitted through FormSubmit and delivered to our company inbox. FormSubmit processes this information on our behalf. Optional cookie choices are stored locally on your device.</p><p>For privacy questions or requests concerning your information, contact support@scorpioanalytics.com.</p></div></div>
    <script src="/site.js" defer></script>  </main>;
}

