const services = [
  { number: "01", title: "Software & SaaS", copy: "Purpose-built platforms, customer portals, and SaaS products engineered to scale with your ambition.", tags: ["Product strategy", "Web & mobile", "Cloud architecture"] },
  { number: "02", title: "AI & Automation", copy: "Practical AI agents and intelligent workflows that remove friction from the work your team does every day.", tags: ["AI agents", "Workflow automation", "Data intelligence"] },
  { number: "03", title: "Growth & Advertising", copy: "Connected campaigns, content, and performance systems that turn attention into measurable momentum.", tags: ["Digital strategy", "Paid media", "Conversion design"] },
  { number: "04", title: "Commerce & Marketplaces", copy: "Digital storefronts and marketplace experiences designed to make discovery, purchase, and loyalty feel effortless.", tags: ["E-commerce", "Marketplaces", "Growth operations"] },
];
const capabilities = ["Web applications", "SaaS platforms", "AI agents", "Process automation", "IT solutions", "Performance marketing", "E-commerce", "Analytics"];
const clientScenes = [
  { title: "Product teams", label: "Software & SaaS", image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=82", alt: "A diverse product team collaborating around a table" },
  { title: "Technology leaders", label: "AI & Automation", image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=82", alt: "Technology professionals working together in a modern office" },
  { title: "Commerce builders", label: "E-commerce", image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=82", alt: "Customer using a digital commerce payment experience" },
  { title: "Growth partners", label: "Digital growth", image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=82", alt: "Business leaders meeting to discuss a growth strategy" },
];
export default function Home() {
  return <main>
    <nav className="nav"><a className="brand" href="#top" aria-label="Scorpio Analytics home"><span className="logo-crop"><img src="/scorpio-logo.png" alt="Scorpio Analytics" /></span></a><div className="nav-links" aria-label="Primary navigation"><a href="#services">Expertise</a><a href="#approach">Approach</a><a href="#contact">Contact</a></div><a className="nav-cta" href="#contact">Start a project <span>↗</span></a></nav>
    <section className="hero" id="top"><div className="hero-kicker"><span className="pulse"/> Digital systems for ambitious businesses</div><h1>We build the<br/>advantage <em>next.</em></h1><div className="hero-bottom"><p>Software, AI, growth, and commerce—designed as one connected engine for what your business becomes next.</p><a className="circle-link" href="#services" aria-label="Explore our expertise">↓</a></div><div className="orbit" aria-hidden="true"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-core">S<span>A</span></div><span className="orbit-label label-one">BUILD</span><span className="orbit-label label-two">AUTOMATE</span><span className="orbit-label label-three">GROW</span></div></section>
    <section className="signal-strip" aria-label="Capabilities"><div className="signal-track">{[...capabilities,...capabilities].map((item,index)=><span key={`${item}-${index}`}>{item} <b>✦</b></span>)}</div></section>
    <section className="services section" id="services"><div className="section-intro"><span className="eyebrow">01 / What we do</span><div><h2>One partner.<br/><i>Every digital lever.</i></h2><p>We connect technology, intelligence, and growth so every investment compounds instead of operating in a silo.</p></div></div><div className="service-grid">{services.map(service=><a className="service-card" key={service.number} href="#contact" aria-label={`Discuss ${service.title} with Scorpio Analytics`}><div className="card-top"><span>{service.number}</span><span className="card-arrow">↗</span></div><h3>{service.title}</h3><p>{service.copy}</p><div className="tags">{service.tags.map(tag=><span key={tag}>{tag}</span>)}</div></a>)}</div></section>
    <section className="client-gallery section" id="clients">
      <div className="section-intro gallery-intro"><span className="eyebrow">02 / Who we build for</span><div><h2>Built around people.<br/><i>Designed for progress.</i></h2><p>We partner with the teams turning ambitious ideas into useful products, efficient operations, and sustainable growth.</p></div></div>
      <div className="client-grid">{clientScenes.map((scene,index)=><a className={`client-image card-${index+1}`} key={scene.title} href="#contact" aria-label={`Discuss solutions for ${scene.title}`}><img src={scene.image} alt={scene.alt} loading="lazy"/><div className="client-caption"><span>{scene.label}</span><h3>{scene.title}</h3><b>0{index+1}</b></div></a>)}</div>
      <p className="image-note">Representative imagery of the teams and industries we serve.</p>
    </section>
    <section className="manifesto"><div className="manifesto-number">02 / OUR POINT OF VIEW</div><p>Technology should not just support the business.</p><h2>It should move it.</h2><div className="manifesto-note"><span>STRATEGY</span><i>→</i><span>SYSTEMS</span><i>→</i><span>SCALE</span></div></section>
    <section className="approach section" id="approach"><div className="section-intro approach-intro"><span className="eyebrow">03 / How we work</span><div><h2>Clarity before code.<br/><i>Outcomes before output.</i></h2></div></div><div className="steps"><article><span>01</span><div><h3>Find the leverage</h3><p>We map the opportunity, the bottlenecks, and the shortest path to meaningful impact.</p></div></article><article><span>02</span><div><h3>Build the system</h3><p>Cross-functional teams turn the strategy into a focused, resilient digital product.</p></div></article><article><span>03</span><div><h3>Compound the value</h3><p>We measure, refine, and scale what works—creating momentum beyond the initial launch.</p></div></article></div></section>
    <section className="contact" id="contact"><span className="eyebrow light">04 / Let’s make it real</span><div className="contact-content"><h2>Your next advantage<br/>starts with a <i>conversation.</i></h2><a className="contact-button" href="mailto:hello@scorpioanalytics.com"><span>Tell us what’s next</span><b>↗</b></a></div><footer><a className="brand footer-brand" href="#top"><span className="logo-crop footer-logo"><img src="/scorpio-logo.png" alt="Scorpio Analytics" /></span></a><div className="footer-meta"><a href="https://www.linkedin.com/company/142884752/" target="_blank" rel="noreferrer">LinkedIn ↗</a><span>© {new Date().getFullYear()} Scorpio Analytics</span></div></footer></section>
  </main>;
}

