const services = {
  "software-saas": { eyebrow: "Software development and SaaS", title: "Software and SaaS products built to scale.", intro: "Scorpio Analytics designs and develops secure web applications, customer portals, internal platforms, and subscription software for growing businesses.", image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1800&q=84", outcomes: ["Product discovery and technical strategy", "Web and mobile application development", "Cloud architecture and integrations", "SaaS modernization and optimization"] },
  "ai-automation": { eyebrow: "Artificial intelligence and automation", title: "AI automation that turns work into momentum.", intro: "We build practical AI agents, intelligent workflows, and data-enabled automation that reduce repetitive work and help teams make faster, better decisions.", image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1800&q=84", outcomes: ["AI agent strategy and implementation", "Workflow and process automation", "Knowledge search and intelligent assistants", "Data intelligence and decision systems"] },
  "digital-growth": { eyebrow: "Digital marketing and advertising", title: "Connected digital growth systems that perform.", intro: "Scorpio Analytics combines strategy, content, paid media, analytics, and conversion design to turn audience attention into measurable business growth.", image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1800&q=84", outcomes: ["Digital growth strategy", "Performance marketing and paid media", "Conversion-focused web experiences", "Campaign analytics and optimization"] },
  "ecommerce-marketplaces": { eyebrow: "E-commerce and marketplaces", title: "Commerce experiences designed for discovery and loyalty.", intro: "We create online storefronts, marketplace platforms, and connected commerce operations that make buying simple and give businesses room to grow.", image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1800&q=84", outcomes: ["E-commerce experience design", "Storefront and marketplace development", "Payments and business integrations", "Commerce analytics and growth operations"] },
} as const;
export type ServiceSlug = keyof typeof services;
export default function ServiceDetail({slug}:{slug:ServiceSlug}){
  const service=services[slug];
  const schema={"@context":"https://schema.org","@type":"Service",name:service.eyebrow,provider:{"@type":"Organization",name:"Scorpio Analytics",url:"https://scorpioanalytics.com/"},areaServed:"Worldwide",description:service.intro};
  return <main className="service-page"><nav className="nav"><a className="brand" href="/" aria-label="Scorpio Analytics home"><span className="logo-crop"><img src="/favicon.png" alt="Scorpio Analytics logo"/></span><span className="brand-name">Scorpio Analytics</span></a><div className="nav-links"><a href="/#about">About</a><a href="/#services">Expertise</a><a href="/#approach">Approach</a></div><a className="nav-cta" href="/#contact">Contact us <span>↗</span></a></nav><section className="service-hero"><div><span className="eyebrow">{service.eyebrow}</span><h1>{service.title}</h1><p>{service.intro}</p><a className="detail-cta" href="mailto:support@scorpioanalytics.com">Discuss your project <span>↗</span></a></div><img src={service.image} alt={service.eyebrow}/></section><section className="service-outcomes"><span className="eyebrow">What we deliver</span><h2>Focused capabilities.<br/><i>Measurable outcomes.</i></h2><div>{service.outcomes.map((item,index)=><article key={item}><span>0{index+1}</span><h3>{item}</h3></article>)}</div></section><section className="service-next"><h2>Ready to build<br/><i>what comes next?</i></h2><a href="mailto:support@scorpioanalytics.com">support@scorpioanalytics.com <span>↗</span></a></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main>
}